### ISSUE TITLE
Render HTML string in Paragraph

### ISSUE THREAD

**Issue by bmmule** [dolanmiu/docx#791] opened 2021-03-02 12:45 UTC
I have a string, which contains html in it. I want to render the html string as it is in document generated. Please can you suggest how can I do it.

The string example: 
`'<ul><li>Performed various administrative and clerical tasks as needed.</li><li>Served as a support for the entire office staff.</li><li>Monitored &amp; observed animals for signs of illness &amp; reported symptoms to superiors.</li><li>Created online pet profiles for potential adopters.</li><li>Collected and recorded adoption fees.</li></ul>'`

Expected result:
●	Performed various administrative and clerical tasks as needed.
●	Served as a support for the entire office staff.
●	Monitored &amp; observed animals for signs of illness &amp; reported symptoms to superiors.
●	Created online pet profiles for potential adopters.
●	Collected and recorded adoption fees.

I was able to do the above with some string manipulations, but need to know if there is any way, I can render the HTML in string without any changes.

**Comment by dolanmiu** [comment] 2021-03-03 15:12
Sorry not possible, and is a duplicate of:

https://github.com/dolanmiu/docx/issues/563

Can even Microsoft Word do this? This feature might even be out of scope of Microsoft Word itself

**Closed by dolanmiu** 2021-03-03 15:12 UTC
