### ISSUE TITLE
[Word 2007] Support for Images or workaround

### ISSUE THREAD

**Issue by shahbazkhan054** [dolanmiu/docx#525] opened 2020-04-10 06:00 UTC
Hello @dolanmiu ,

I have been looking into openxml image format difference between word 2007 & 2008.
I couldn't find anything in specific which is cause of crashing of docx in word 2007.

I will keep sharing my finding on this thread

Could you please help me with any start point where I can fix this and raise PR?

**Comment by dolanmiu** [comment] 2021-03-07 18:03
Duplicate of: https://github.com/dolanmiu/docx/issues/394

**Closed by dolanmiu** 2021-03-07 18:03 UTC
