### ISSUE TITLE
Table borders

### ISSUE THREAD

**Issue by faradoxuz** [dolanmiu/docx#253] opened 2019-01-21 17:04 UTC
Is there any method for removing table borders by default or with one method for certain table? :)

**Comment by dolanmiu** [comment] 2019-01-21 19:53
Check out https://github.com/dolanmiu/docx/blob/master/demo/demo20.ts

**Comment by dolanmiu** [comment] 2019-01-21 19:53
You can do BorderStyle.NONE to achieve the effect you want

**Comment by entrptaher** [comment] 2019-01-23 22:30
I tested the demo20 and all other table styles. The demo failed to run. 
:/ 

```
.addParagraph(new Paragraph("Hello"))
     ^

TypeError: table.getCell(...).addParagraph is not a function
    at Object.<anonymous> (/home/taher/docx/app.js:9:6)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:499:15)
    at startMainThreadExecution (internal/bootstrap/node.js:436:3)
```

I cannot apply any table styles and all methods specified on the demo is not working. 

What am I missing?

**Comment by dolanmiu** [comment] 2019-01-24 00:36
I recently changed `addContent` to `addParagraph` so that's most likely why

Try a fresh clone of the repo, or do `npm run build` to rebuild. 

On master it definitely works, otherwise my CI would fail.

I just checked right now for sanity, and i can confirm demo 20 does indeed work

**Comment by dolanmiu** [comment] 2019-01-25 13:05
> Some functions still did not work properly though.
Also, I had to create a function for the table style.

What functions?

**Comment by entrptaher** [comment] 2019-01-27 00:54
Later I will create another issue with other problems, features and missing documentation.

**Comment by dolanmiu** [comment] 2019-01-27 17:36
ok sure

Thanks

**Comment by dolanmiu** [comment] 2019-02-26 22:48
Closing because this thread is getting irrelevant

For reference:

To modify borders in `4.7.1`: https://github.com/dolanmiu/docx/blob/4.7.1/demo/demo20.ts

**Closed by dolanmiu** 2019-02-26 22:48 UTC

**Comment by GarrettGeorge** [comment] 2019-05-06 23:46
For the record in `4.7.1` 
```js
cell.CellProperties.Borders
        .addTopBorder(BorderStyle.NONE)
        .addBottomBorder(BorderStyle.NONE)
        .addStartBorder(BorderStyle.NONE)
        .addEndBorder(BorderStyle.NONE);
```

Does not remove borders as expected.

**Comment by mbrevda** [comment] 2019-06-11 21:28
@entrptaher  can you share how you removed the borders? As above, this doesn't seem to be working

**Comment by mbrevda** [comment] 2019-06-11 22:31
This seems to remove all the borders from a table:

```js
const header = doc.Header.createTable(1, 3)
header.properties.root[1] = [] //clear border
```

**Comment by entrptaher** [comment] 2019-06-12 04:48
Instead of setting the properties like that, I discovered it would be much more efficient to apply styles.

```js
const docx = require('docx');
const fs = require('fs');

const { Attributes, XmlComponent } = require('docx');

class StyleCreator extends XmlComponent {
  constructor(styleId, mainId) {
    super(mainId);
    this.styleId = styleId;
    this.root.push(
      new Attributes({
        val: styleId,
      }),
    );
    return this;
  }
}

docx.Table.prototype.addTableStyle = function addTableStyle(styleId) {
  this.properties.root.push(new StyleCreator(styleId, 'w:tblStyle'));
  return this;
};

docx.Table.prototype.createCell = function createCell(row, column, text) {
  const cell = this.getCell(row, column);
  cell.properties.setWidth('50%', docx.WidthType.PERCENTAGE);
  cell.addParagraph(new docx.Paragraph(text));
  return this;
};
```

Then I could use some styles like this,

```js
const table = doc.createTable(10, 10, 10);
table.addTableStyle('TableGridLight');
```

This way I could apply any style to any kind of element.

I did not have had time to create a PR or a separate repo explaining this yet.

**Comment by davidcheal** [comment] 2019-06-20 03:13
Hi @entrptaher I'm trying to extend the table as you outlined but get 'Class constructor XmlComponent cannot be invoked without 'new'' when I run it. Any idea whats causing this?

**Comment by Treverix** [comment] 2019-06-20 18:07
@entrptaher Thank you! You saved my day. Your code work, I FINALLY got rid of my borders. It should REALLY by added to the code base.

**Comment by dolanmiu** [comment] 2019-06-21 12:01
It is planned to be added!

**Comment by quirinpa** [comment] 2021-03-09 10:59
@entrptaher I would like to set my table's styles using a similar method but its not working for me under current version. Any tips?

**Comment by dolanmiu** [comment] 2021-03-09 15:18
Check out:

https://github.com/dolanmiu/docx/blob/master/demo/20-table-cell-borders.ts

`w:tblStyle` isnt in v5 yet

Planned for v6

**Comment by henry132109** [comment] 2021-08-03 10:33
> @quirinpa Check out:
> 
> https://github.com/dolanmiu/docx/blob/master/demo/20-table-cell-borders.ts
> 
> `w:tblStyle` isnt in v5 yet
> 
> Planned for v6

Could you add an example for BorderStyle.NONE as well?
