### ISSUE TITLE
Placeholders in Templates?

### ISSUE THREAD

**Issue by elementalPRESS** [dolanmiu/docx#608] opened 2020-08-04 08:21 UTC
I know that dolanmiu/docx suports templates, which is wonderful. But is there also a possibility to use placeholders in these templates?

What I'm looking for is a way to fill e.g. a header and footer with values. The format (style) shall be taken from the template. Is this possible with docx.js?

Thx and regards,
Lars

**Comment by dolanmiu** [comment] 2020-08-08 00:34
I am not sure, I have not tried, the templating feature was not written by me

Maybe this example can shed some light?

https://github.com/dolanmiu/docx/blob/master/demo/30-template-document.ts

**Comment by elementalPRESS** [comment] 2020-08-15 06:09
> I am not sure, I have not tried, the templating feature was not written by me
> 
> Maybe this example can shed some light?
> 
> https://github.com/dolanmiu/docx/blob/master/demo/30-template-document.ts

The demo doesn't work. It generates a word document but the template is not used in terms of - template is not shown

**Comment by dolanmiu** [comment] 2020-10-26 20:25
Duplicate of https://github.com/dolanmiu/docx/issues/489

Closing

**Closed by dolanmiu** 2020-10-26 20:25 UTC
