### ISSUE TITLE
Display alert in Ms Word while opening doc

### ISSUE THREAD

**Issue by Veeresh870** [dolanmiu/docx#680] opened 2020-11-06 10:30 UTC
Hi,
I am getting a warning popup in Ms word while opening document, Is there any ways to suppress this ?

![Screenshot (256)](https://user-images.githubusercontent.com/73984293/98356125-21ff1a00-2049-11eb-8fc5-15fc774212dc.png)

**Comment by dolanmiu** [comment] 2020-11-06 11:39
Duplicate of https://github.com/dolanmiu/docx/issues/380

**Closed by dolanmiu** 2020-11-06 11:39 UTC
