### ISSUE TITLE
Hyperlink in footer make document broken

### ISSUE THREAD

**Issue by kwyz** [dolanmiu/docx#532] opened 2020-04-27 08:36 UTC
When I add a hyperlink to the footer, the document breaks, but if I add the hyperlink to the body of the document everything is fine, using the same methodology. How can I add the hyperlink in the footer. Here is the warning message

![Capture](https://user-images.githubusercontent.com/23142517/80351445-008fcb00-887b-11ea-856f-2820a463166d.PNG)

And the code sequence I used

```javascript
 public annex: Document = new Document({
        hyperlinks: {
            linkToVerify: {
                link: "http://www.example.com",
                text: "Verify here",
                type: HyperlinkType.EXTERNAL,
            },
           
        },
        styles: new Styles().getCustomStyles(),
    });

private addAnnexFooter(): void {
        this.annex.addSection({
            footers: {
                default: new Footer({
                    children: [
                        new Paragraph({
                            text: "This file was signed",
                            alignment: AlignmentType.RIGHT
                        }),
                        new Paragraph({
                            children: [
                                new TextRun("You can verify signature here: "),
                                new HyperlinkRef("linkToVerify")
                            ],
                            alignment: AlignmentType.RIGHT
                        }),
                 
                    ],
                }),
            },
            children: []
        });
    }
```

Thanks for this awesome library.

**Comment by microbit-matt-hillsdon** [comment] 2020-04-28 15:02
Stumbled across this today too. This appears to be down to assuming the underlying "relationship" that needs to be created for the hyperlink goes in the main set in document.xml.rels rather than the footer specific set.

**Comment by BrentFarese** [comment] 2020-12-27 02:34
I can confirm this is occurring for me too.  @dolanmiu any ideas on the cause of the issue?  I can consider submitting a PR with some guidance.  Thanks!

**Comment by dolanmiu** [comment] 2020-12-31 03:20
@BrentFarese please do!

**Comment by dolanmiu** [comment] 2021-03-01 03:31
This issue will be fixed in:

https://github.com/dolanmiu/docx/pull/785

Hyperlinks will work in headers and footers now!

The root cause was because the hyperlink references were being added in the document.xml ref file rather than the footer and header.xml ref files respectively

**Closed** 2021-03-01 03:39 UTC
