### ISSUE TITLE
Example 28-table-of-contents.ts is not working

### ISSUE THREAD

**Issue by caotrongtin99** [dolanmiu/docx#1225] opened 2021-10-12 09:36 UTC
Hi,
I run example code but index block do not show.

**Comment by huzaifa3115** [comment] 2021-11-19 16:35
Same here with me.

**Comment by huzaifa3115** [comment] 2021-11-19 16:35
Did you get any solution?

**Comment by dolanmiu** [comment] 2022-07-13 10:18
Duplicate of:

https://github.com/dolanmiu/docx/issues/748

**Closed by dolanmiu** 2022-07-13 10:18 UTC

**Comment by hahaXiaoxin** [comment] 2023-11-23 11:30
Have one get any solution?I use example [of 28-table-contents.ts](https://github.com/dolanmiu/docx/issues/1225#top) but no catalogue On November 23 2023,the docx version is @8.2.4
