### ISSUE TITLE
.docx file created via docx module is not opening.

### ISSUE THREAD

**Issue by ADITI1001** [dolanmiu/docx#64] opened 2018-03-10 08:30 UTC
I created a .docx file via this module, but it does not open. When I double-click on the file, following things happen.
![screenshot 7](https://user-images.githubusercontent.com/34959060/37240039-2e7aeea8-246b-11e8-9977-3e057b3929bf.png)
![screenshot 8](https://user-images.githubusercontent.com/34959060/37240040-2eac65b4-246b-11e8-9a9c-7a3229175cb8.png)
![screenshot 9](https://user-images.githubusercontent.com/34959060/37240041-2ee36618-246b-11e8-98f1-8ccf03f68f2c.png)

**Comment by dolanmiu** [comment] 2018-03-10 16:53
Can you send me some code to reproduce the document so I can dig deeper?

**Comment by ADITI1001** [comment] 2018-03-10 21:10
const doc = new docx.Document(undefined, {
    top: 700,
    right: 700,
    bottom: 700,
    left: 700
});

    doc.Styles.createParagraphStyle('Heading1', 'Heading 1')
        .basedOn("Normal")
        .next("Normal")
        .quickFormat()
        .font('Calibri')
        .size(52)
        .center()
        .bold()
        .color(000000)
        .spacing({line: 340})
        .underline('single', '000000');

    doc.Styles.createParagraphStyle('Heading2', 'Heading 2')
        .basedOn("Normal")
        .next("Normal")
        .font('Calibri')
        .quickFormat()
        .size(26)
        .bold()
        .spacing({line: 340});

    doc.Styles.createParagraphStyle('Heading3', 'Heading 3')
        .basedOn("Normal")
        .next("Normal")
        .font('Calibri')
        .quickFormat()
        .size(26)
        .bold()
        .spacing({line: 276});

    doc.Styles.createParagraphStyle('Heading4', 'Heading 4')
        .basedOn("Normal")
        .next("Normal")
        .justified()
        .font('Calibri')
        .size(26)
        .bold();

    doc.Styles.createParagraphStyle('normalPara', 'Normal Para')
        .basedOn("Normal")
        .next("Normal")
        .font('Calibri')
        .quickFormat()
        .leftTabStop(453.543307087)
        .maxRightTabStop(453.543307087)
        .size(26)
        .spacing({line: 276, before: 20 * 72 * .1, after: 20 * 72 * .05});

    doc.Styles.createParagraphStyle('normalPara2', 'Normal Para2')
        .basedOn("Normal")
        .next("Normal")
        .quickFormat()
        .font('Calibri')
        .size(26)
        .justified()
        .spacing({line: 276, before: 20 * 72 * .1, after: 20 * 72 * .05});

    doc.Styles.createParagraphStyle('aside', 'Aside')
        .basedOn('Normal')
        .next('Normal')
        .color('999999')
        .italics()
        .indent(720)
        .spacing({line: 276});

    doc.Styles.createParagraphStyle('wellSpaced', 'Well Spaced')
        .basedOn('Normal')
        .spacing({line: 276, before: 20 * 72 * .1, after: 20 * 72 * .05});

    doc.Styles.createParagraphStyle('ListParagraph', 'List Paragraph')
        .quickFormat()
        .basedOn('Normal');

    doc.createImage("angular/assets/images/LOGO-expand.png");
    doc.createParagraph('HEADING').heading1().center();

    doc.Footer.createParagraph('1').style('normalPara').right();

    doc.createParagraph('Ref. :').style('normalPara');
    doc.createParagraph('Date :').style('normalPara');

    doc.createParagraph('To,').style('normalPara');
    doc.createParagraph('The Superindenting Engineer,(O &
M)').style('normalPara');

    doc.createParagraph('Sub : ').style('normalPara');

    doc.createParagraph('Ref. : ').style('normalPara');

    doc.createParagraph('Sir,').style('normalPara');

    doc.createParagraph('BRIEF DESCRIPTION').style('normalPara');

    var table = new docx.Table(4, 4);
var contentParagraph = table.getRow(0).getCell(0).addContent(new
docx.Paragraph('Pole No.'));
table.properties.width = 10000;
doc.addTable(table);

arrboth.forEach(function(item){
const para = doc.createParagraph();
para.createTextRun(doc.createImage(item.image))
//const image = doc.createImage(item.image);
para.properties.width = 60;
para.properties.height = 90;
    doc.createParagraph(item.comment).style('normalPara2');
})

    var exporter = new docx.LocalPacker(doc);
exporter.pack('My Document');


Thank You!

Aditi Dwivedi

**Comment by dolanmiu** [comment] 2018-03-10 23:12
I cannot reproduce the error you are having, I have created a new demo called `demo11.js` on `master` based on what your problem, and it works perfectly well 100%

**Comment by ADITI1001** [comment] 2018-03-11 05:31
Okay.
Also, the table that I am creating in the above mentioned code does not
shows any boundaries/ borders. And, the images that I am adding, runs out
of the page. So, till this time I was thinking that it was because of the
error in the document, that was not being created properly.
I also read in one of the issues that border in table and resizing of
images had not been implemented so far. So can you please suggest me some
way of doing that? I don't need to make the template too fancy, just a
default border that shows the structure of the table and images that
adjusts within the page.
Also, is there a way to add page numbers automatically?

Thank you!

ADITI DWIVEDI

**Comment by dolanmiu** [comment] 2018-03-11 22:20
Tables were not done by me, and when I last checked there was no borders, I will add this functionality soon, and it seems important

Resize the image with photoshop, then re-import. I will work on resizable images

**Comment by dolanmiu** [comment] 2018-03-22 23:07
@ADITI1001 Tables now have borders by default :) enjoy

Released in `3.2.1` :)

**Closed by dolanmiu** 2018-03-22 23:07 UTC
