### ISSUE TITLE
how to create RTL document?

### ISSUE THREAD

**Issue by majeeddl** [dolanmiu/docx#227] opened 2018-12-28 10:07 UTC

**Comment by dolanmiu** [comment] 2018-12-28 13:21
Follow this example:

https://github.com/dolanmiu/docx/blob/master/demo/demo22.ts

**Comment by majeeddl** [comment] 2018-12-28 13:32
Can I set rtl to document or table?

**Comment by dolanmiu** [comment] 2018-12-28 15:05
You need to set it to every TextRun like the example above

**Comment by majeeddl** [comment] 2018-12-28 15:36
I want to set table direction like following image

![2018-12-28_19-03-49](https://user-images.githubusercontent.com/472520/50520068-80fdba80-0ad3-11e9-96b5-2fff35ee23ce.jpg)

Can I do this action?

**Comment by dolanmiu** [comment] 2021-03-05 03:17
This will be in `6.0.0` with this PR: https://github.com/dolanmiu/docx/pull/795!

It is a duplicate of: https://github.com/dolanmiu/docx/issues/751

**Closed by dolanmiu** 2021-03-05 03:17 UTC
Labels: feature request
