### ISSUE TITLE
Paragraph Text Frames not maintaining Alignment

### ISSUE THREAD

**Issue by kingcodefish** [dolanmiu/docx#2366] opened 2023-09-29 17:21 UTC
Paragraph text frames are not maintaining their alignment when exported. Here is the following test code:
```
const doc = new Document({
  sections: [
    {
      properties: {},
      children: [
        new Paragraph({
          frame: {
            position: {
              x: 0,
              y: 0,
            },
            width: 4000,
            height: 1000,
            anchor: {
              horizontal: FrameAnchorType.PAGE,
              vertical: FrameAnchorType.PAGE,
            },
            alignment: {
              x: HorizontalPositionAlign.RIGHT,
              y: VerticalPositionAlign.TOP,
            }
          },
          alignment: AlignmentType.RIGHT,
          children: [
            new TextRun("test")
          ],
        }),
      ],
    },
  ],
});
```
producing the following output. Running docx@8.2.2.
![image](https://github.com/dolanmiu/docx/assets/8534813/2df50b08-654c-47cf-9515-3d2c3d4aa8a3)

**Comment by anti-the-social** [comment] 2023-10-16 08:22
Seems to be duplicate of this issue: https://github.com/dolanmiu/docx/issues/933

**Comment by dolanmiu** [comment] 2023-12-25 03:07
Closing as duplicate

**Closed by dolanmiu** 2023-12-25 03:07 UTC
