### ISSUE TITLE
How to parse raw HTML from richtext like tinymce

### ISSUE THREAD

**Issue by subhaneetshrestha** [dolanmiu/docx#880] opened 2021-04-05 08:18 UTC
Is there anyway to add html in string to be parsed when added to the docx? Currently it just prints the raw HTML.

**Comment by dolanmiu** [comment] 2021-04-06 01:25
Duplicate of:

https://github.com/dolanmiu/docx/issues/820

**Closed by dolanmiu** 2021-04-06 01:25 UTC
