### ISSUE TITLE
Multiple tables treated as a single table with different numbers of table cells

### ISSUE THREAD

**Issue by c-bibek-shrestha** [dolanmiu/docx#494] opened 2020-01-20 09:33 UTC
I tried to add two tables simultaneously, but the output in the word document is a single table with variable table cells.
> **Environment:**
> * Angular CLI
> *  docx@5.0.2

```ts
import { Component } from "@angular/core";
import {
  Document,
  TableRow,
  TableCell,
  Paragraph,
  HeadingLevel,
  VerticalAlign,
  Table,
  PageOrientation,
  Packer
} from "docx";
import { saveAs } from "file-saver";

@Component({
  selector: "my-app",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  name = "Angular";

  public clickFunction() {
    const doc = new Document();
    const table = new Table({
      rows: [
        new TableRow({
          children: [
            new TableCell({
              children: [
                new Paragraph({
                  text: "safdasdfsadfsadf"
                }),
                new Paragraph({
                  text: "safdasdfsadfsadf"
                })
              ],
              verticalAlign: VerticalAlign.CENTER
            })
          ]
        }),
        new TableRow({
          children: [
            new TableCell({
              children: [
                new Paragraph({
                  text:
                    "Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah",
                  heading: HeadingLevel.HEADING_1
                })
              ]
            }),
            new TableCell({
              children: [
                new Paragraph({
                  text: "This text should be in the middle of the cell"
                })
              ],
              verticalAlign: VerticalAlign.CENTER
            })
          ]
        })
      ]
    });
    const table2 = new Table({
      rows: [
        new TableRow({
          children: [
            new TableCell({
              children: [
                new Paragraph({
                  text: "Blah Blah Blah Blah Blah Blah Blah Blah",
                  heading: HeadingLevel.HEADING_1
                })
              ]
            }),
            new TableCell({
              children: [
                new Paragraph({
                  text: "This text should be in the middle of the cell"
                })
              ],
              verticalAlign: VerticalAlign.CENTER
            }),
            new TableCell({
              children: [
                new Paragraph({
                  text: "This text should be in the middle of the cell"
                })
              ],
              verticalAlign: VerticalAlign.CENTER
            })
          ]
        })
      ]
    });
    doc.addSection({
      margins: {
        top: 720,
        right: 720,
        left: 720,
        bottom: 720
      },
      size: {
        orientation: PageOrientation.LANDSCAPE
      },
      children: [table, table2]
    });
    Packer.toBlob(doc, false).then(blob => {
      const mimeType =
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
      const docblob = blob.slice(0, blob.size, mimeType);
      saveAs(docblob, "Test.docx");
    });
  }
}
```

Above code should give me two different tables but I get something like this:

![shoulbe](https://user-images.githubusercontent.com/59474378/72714938-adc9b780-3b97-11ea-918b-f2e47f081d19.jpg)

Am i missing something or is it a bug?

**Comment by dolanmiu** [comment] 2020-01-20 10:56
It is two tables I think, try add an empty paragraph in between, and then show me the result:

```ts
      children: [table, new Paragraph(''), table2]

```

**Comment by c-bibek-shrestha** [comment] 2020-01-20 11:47
> It is two tables I think, try add an empty paragraph in between, and then show me the result:
> 
> ```ts
>       children: [table, new Paragraph(''), table2]
> ```

An empty paragraph helps, but i think two instances should have two different table nodes. For an instance, the above table with two columns should have taken 100% area, instead it takes relative to the three column table.

**Comment by dolanmiu** [comment] 2021-03-08 04:52
I see your point, but this is actually a feature of Word, not a bug

I did not add or remove any extra features of the rendering, I am making a direct translation from JavaScript to OOXML

Closing

**Closed by dolanmiu** 2021-03-08 04:52 UTC

**Comment by sameerchamankar** [comment] 2024-07-24 14:02
I am facing the same issue. Adding paragraph in between works but gives extra space.
