### ISSUE TITLE
The header and footer of the document do not disappear.

### ISSUE THREAD

**Issue by Gildars** [dolanmiu/docx#678] opened 2020-11-05 23:56 UTC
The footer disappears only if you click on it. 
![Image](https://media.giphy.com/media/pzEi7RSyF9FAGeTP0q/source.gif)

```
doc.addSection({
    margins: {
      header: 0,
      footer: 0,
      top: 0,
      left: 425,
      bottom: 0,
      right: 311,
      gutter: 0,
      mirror: 0
    },
    size: {
      width: 3288,
      height: 16837
    },
    children: [
     // calling some functions
    ]
  })
```

**Comment by dolanmiu** [comment] 2020-11-06 00:02
Ah yes, this is because there is a blank header and footer created by default always, this needs to be changed

Duplicate of: https://github.com/dolanmiu/docx/issues/251

**Closed by dolanmiu** 2020-11-06 00:02 UTC
