### ISSUE TITLE
Inline patchDocument replacement 

### ISSUE THREAD

**Issue by pooledge** [dolanmiu/docx#2028] opened 2023-03-22 22:01 UTC
I'm running into a problem where a simple docx template like `Hello {{name}}, how are you?`, being patched with:

```ts
patchDocument(fs.readFileSync('.tmp/test.docx'), {
	patches: {
		name: {
			type: PatchType.PARAGRAPH,
			children: [new TextRun({ text: 'Max' })]
		}
	}
}).then((doc) => {
	fs.writeFileSync(fileName, doc);
});
```
becomes `MaxHello, howare you?`

Is it a known thing? `simple-template.docx` from demos works fine for me though, but only as long as I am not moving patchable placeholders around.

I am editing using latest MS Word on Mac.

**Comment by dolanmiu** [comment] 2023-03-22 22:44
Can you send me the test.docx? and I will investigate

**Comment by pooledge** [comment] 2023-03-23 07:42
Here we go, thank you: https://we.tl/t-O8D2l0ikE2

**Comment by pooledge** [comment] 2023-03-23 15:59
More insights incoming. As soon as I have multiple patches i.e. multiple keys in `patches{}`:

```bash
TypeError: Cannot read properties of undefined (reading 'text')
    at Ba (/site/node_modules/docx/build/index.js:2:327108)
    at Ha (/site/node_modules/docx/build/index.js:2:328126)
    at i (/site/node_modules/docx/build/index.js:2:330638)
    at i.next (<anonymous>)
    at o (/site/node_modules/docx/build/index.js:2:332428)
```

Looks like patching only one placeholder e.g. `first-name` is thus malforming adjacent others: `{{salutation}}{{first-name}}{{last-name}}` -> `Max{{{{last-name}}`

**Comment by dolanmiu** [comment] 2023-03-23 16:04
Nice observations, will look into this tonight

**Comment by dolanmiu** [comment] 2023-03-23 21:02
Created a PR to fix the issue and wrote tests around it:

https://github.com/dolanmiu/docx/pull/2032

**Comment by pooledge** [comment] 2023-03-24 08:25
May I reopen?

Here is the [minimum docx](https://github.com/dolanmiu/docx/files/11059898/test.docx) to reproduce the error below:

> As soon as I have multiple patches i.e. multiple keys in `patches{}`:
> 
> ```shell
> TypeError: Cannot read properties of undefined (reading 'text')
>     at Ba (/site/node_modules/docx/build/index.js:2:327108)
>     at Ha (/site/node_modules/docx/build/index.js:2:328126)
>     at i (/site/node_modules/docx/build/index.js:2:330638)
>     at i.next (<anonymous>)
>     at o (/site/node_modules/docx/build/index.js:2:332428)
> ```

My patches:
```
{
	"salutation": {
		"type": "paragraph",
		"children": [
			{
				"rootKey": "w:r",
				"root": [
					{
						"rootKey": "w:rPr",
						"root": [
							{
								"rootKey": "w:rFonts",
								"root": [
									{
										"rootKey": "_attr",
										"root": {
											"ascii": "Trebuchet MS",
											"cs": "Trebuchet MS",
											"eastAsia": "Trebuchet MS",
											"hAnsi": "Trebuchet MS"
										},
										"xmlKeys": {
											"ascii": "w:ascii",
											"cs": "w:cs",
											"eastAsia": "w:eastAsia",
											"hAnsi": "w:hAnsi",
											"hint": "w:hint"
										}
									}
								]
							}
						]
					},
					{
						"rootKey": "w:t",
						"root": [
							{
								"rootKey": "_attr",
								"root": { "space": "preserve" },
								"xmlKeys": { "space": "xml:space" }
							},
							"Mr"
						]
					}
				],
				"properties": {
					"rootKey": "w:rPr",
					"root": [
						{
							"rootKey": "w:rFonts",
							"root": [
								{
									"rootKey": "_attr",
									"root": {
										"ascii": "Trebuchet MS",
										"cs": "Trebuchet MS",
										"eastAsia": "Trebuchet MS",
										"hAnsi": "Trebuchet MS"
									},
									"xmlKeys": {
										"ascii": "w:ascii",
										"cs": "w:cs",
										"eastAsia": "w:eastAsia",
										"hAnsi": "w:hAnsi",
										"hint": "w:hint"
									}
								}
							]
						}
					]
				}
			}
		]
	},
	"first-name": {
		"type": "paragraph",
		"children": [
			{
				"rootKey": "w:r",
				"root": [
					{
						"rootKey": "w:rPr",
						"root": [
							{
								"rootKey": "w:rFonts",
								"root": [
									{
										"rootKey": "_attr",
										"root": {
											"ascii": "Trebuchet MS",
											"cs": "Trebuchet MS",
											"eastAsia": "Trebuchet MS",
											"hAnsi": "Trebuchet MS"
										},
										"xmlKeys": {
											"ascii": "w:ascii",
											"cs": "w:cs",
											"eastAsia": "w:eastAsia",
											"hAnsi": "w:hAnsi",
											"hint": "w:hint"
										}
									}
								]
							}
						]
					},
					{
						"rootKey": "w:t",
						"root": [
							{
								"rootKey": "_attr",
								"root": { "space": "preserve" },
								"xmlKeys": { "space": "xml:space" }
							},
							"John"
						]
					}
				],
				"properties": {
					"rootKey": "w:rPr",
					"root": [
						{
							"rootKey": "w:rFonts",
							"root": [
								{
									"rootKey": "_attr",
									"root": {
										"ascii": "Trebuchet MS",
										"cs": "Trebuchet MS",
										"eastAsia": "Trebuchet MS",
										"hAnsi": "Trebuchet MS"
									},
									"xmlKeys": {
										"ascii": "w:ascii",
										"cs": "w:cs",
										"eastAsia": "w:eastAsia",
										"hAnsi": "w:hAnsi",
										"hint": "w:hint"
									}
								}
							]
						}
					]
				}
			}
		]
	}
}
```

Any of those applied separately works okay. Thank you for looking into this!

**Comment by dolanmiu** [comment] 2023-03-24 11:41
Ok, thanks for investigating, I will do investigating my side too and create a fix

**Comment by dolanmiu** [comment] 2023-03-24 15:14
Do you patch with a JSON object, or you do patch with `new TextRun(...)`? etc? Because the former is not supported. Needs to be an object like `TextRun`

**Comment by pooledge** [comment] 2023-03-24 15:20
I am patching like this:

```ts
// lib
export const font = 'Trebuchet MS';
export const getPatches = (fields: { [key: string]: string }) => {
	const patches: { [key: string]: IPatch } = {};

	for (const field in fields) {
		patches[field] = {
			type: PatchType.PARAGRAPH,
			children: [new TextRun({ text: fields[field], font })]
		};
	}

	return patches;
};

// exec
const patches = getPatches({
	salutation: 'Mr',
	'first-name': 'John'
});
```

**Comment by dolanmiu** [comment] 2023-03-28 19:20
I can't seem to reproduce the issue, I have even created a demo here to try and describe the problem, but it worked flawlessly:

https://github.com/dolanmiu/docx/blob/master/demo/88-template-document.ts

Can you send the word document? So I can invesatigate on that?

**Comment by pooledge** [comment] 2023-03-30 19:35
Did you check this file: https://github.com/dolanmiu/docx/files/11059898/test.docx ?
If yes, I guess we can close this. I went the generation path rather than patching.

**Comment by dolanmiu** [comment] 2023-03-30 23:14
Fixed in https://github.com/dolanmiu/docx/pull/2053

Using that example document you provided as well

**Closed** 2023-04-04 21:38 UTC
