### ISSUE TITLE
Table width 100 percentage not working

### ISSUE THREAD

**Issue by allandiego** [dolanmiu/docx#745] opened 2021-01-05 18:07 UTC
Im tring to create a full width table using percentage but no matter what size i set this is the result:
![image](https://user-images.githubusercontent.com/6215050/103682142-37b88f00-4f67-11eb-8d97-9659980d5936.png)

version "docx": "^5.4.1" in nodejs

```ts
import {
  Document,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  Media,
  WidthType,
  AlignmentType,
  TableLayoutType,
  VerticalAlign,
  HeightRule,
  PageBreak,
  TextRun,
} from 'docx';

function createDocument() {
const docx = new Document();

const image1 = Media.addImage(
    docx,
    fs.readFileSync('./public/placeholder-img.jpg'),
    200,
    200,
  );

  const cellImage = new TableCell({
    children: [new Paragraph(image1)],
    width: { size: 50, type: WidthType.PERCENTAGE },
    verticalAlign: VerticalAlign.CENTER,
  });
  const rowPhotos = new TableRow({
    children: [cellImage, cellImage],
  });

  const cellTextColumn1 = new TableCell({
    children: [new Paragraph('Text column 1')],
    width: { size: 50, type: WidthType.PERCENTAGE },
    verticalAlign: VerticalAlign.CENTER,
  });
  const cellTextColumn2 = new TableCell({
    children: [new Paragraph('Text column 2')],
    width: { size: 50, type: WidthType.PERCENTAGE },
    verticalAlign: VerticalAlign.CENTER,
  });
  const rowText = new TableRow({
    children: [cellTextColumn1, cellTextColumn2],
  });

  const table = new Table({
    rows: [rowPhotos, rowText, rowPhotos, rowText, rowPhotos, rowText],
    width: { size: 100, type: WidthType.PERCENTAGE },
    alignment: AlignmentType.CENTER,
    columnWidths: [50, 50],
    layout: TableLayoutType.FIXED,
  });

  docx.addSection({
    children: [table, new PageBreak()],
  });

 Packer.toBuffer(docx).then(buffer => {
    fs.writeFileSync('test.docx', buffer);
  });
}

createDocument();
```

I also tried this issue example code but i get the same behavior
https://github.com/dolanmiu/docx/issues/706

**Comment by dolanmiu** [comment] 2021-01-06 18:14
What word processor are you using?

**Comment by allandiego** [comment] 2021-01-06 18:42
I have tested with google docs / microsoft live word / wordpad. I have done some more tests and removing the images get it to work in the live word but not in google docs

**Comment by sonicwong** [comment] 2021-01-14 04:11
tested with google docs, width is in 1 character width.
tested with LibreOffice, width is 100%.

**Comment by dolanmiu** [comment] 2021-01-14 13:00
Yup this issue has been raised many times before

Duplicate of:

https://github.com/dolanmiu/docx/issues/349

**Closed by dolanmiu** 2021-01-14 13:00 UTC
Labels: bug
