### ISSUE TITLE
Template demo isn't working as expected

### ISSUE THREAD

**Issue by elementalPRESS** [dolanmiu/docx#614] opened 2020-08-11 06:17 UTC
Hi,

what is the template demo (30) doing? I expected that it's possible to create a template and insert my content into that template. But when trying the corresponding demo (https://github.com/dolanmiu/docx/blob/master/demo/30-template-document.ts) a new document is created that just showing "Hello World" without headers and footers from the template.

Is the demo wrong or am I wrong in thinking?

Thx for any help,
Lars

**Comment by HTrayford** [comment] 2020-08-19 19:14
I have had the exact same experience.  Demo 30 behaves identically with or without the templateDocument, as though it is simply ignored when present.

**Comment by dolanmiu** [comment] 2020-10-26 20:26
Duplicate of https://github.com/dolanmiu/docx/issues/489

Closing

**Closed by dolanmiu** 2020-10-26 20:26 UTC
