### ISSUE TITLE
Can't set width on TableCell

### ISSUE THREAD

**Issue by chareice** [dolanmiu/docx#468] opened 2019-12-05 03:11 UTC
In the [Documentation](https://docx.js.org/#/usage/tables?id=options-1)，there is a `width` option in TableCell, but in the d.ts file. the options doesn't have a `width` attribute.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/1624785/70200888-e3cdec00-174f-11ea-8518-34b79d19646e.png">

**Comment by dolanmiu** [comment] 2020-02-27 10:23
Duplicate of https://github.com/dolanmiu/docx/issues/441

I am aware of this issue

**Closed by dolanmiu** 2020-02-27 10:23 UTC
