### ISSUE TITLE
cell rowSpan not work right

### ISSUE THREAD

**Issue by w529456185** [dolanmiu/docx#429] opened 2019-10-14 06:48 UTC
```ts
const table2 = new Table({
    rows: [
        new TableRow({
            width:{
                size:100,
                type:WidthType.PERCENTAGE
            },
            children: [
                new TableCell({
                    children: [new Paragraph("0,0")],
                    rowSpan: 5,
                }),
                new TableCell({
                    children: [new Paragraph("0,1")],
                }),
                new TableCell({
                    children: [new Paragraph("0,2")],
                    columnSpan:2
                }),
                // new TableCell({
                //     children: [new Paragraph("0,3")],
                // }),
                new TableCell({
                    children: [new Paragraph("0,4")],
                }),
                new TableCell({
                    children: [new Paragraph("0,5")],
                }),
            ],
        }),
        new TableRow({
            children: [
                new TableCell({
                    children: [new Paragraph("1,0")],
                }),
                // new TableCell({
                //     children: [new Paragraph("1,1")],
                //     rowSpan: 4,
                // }),
                new TableCell({
                    children: [new Paragraph("1,2")],
                }),
                new TableCell({
                    children: [new Paragraph("1,3")],
                }),
                new TableCell({
                    children: [new Paragraph("1,4")],
                }),
                new TableCell({
                    children: [new Paragraph("1,5")],
                }),
            ],
        }),
        new TableRow({
            children: [
                new TableCell({
                    children: [new Paragraph("2,0")],
                }),
                
                new TableCell({
                    children: [new Paragraph("2,2")],
                }),
                new TableCell({
                    children: [new Paragraph("2,3")],
                }),
                new TableCell({
                    children: [new Paragraph("2,4")],
                }),
                new TableCell({
                    children: [new Paragraph("2,5")],
                }),
            ],
        }),
        new TableRow({
            children: [
                new TableCell({
                    children: [new Paragraph("3,0")],
                }),
                
                new TableCell({
                    children: [new Paragraph("3,2")],
                }),
                new TableCell({
                    children: [new Paragraph("3,3")],
                }),
                new TableCell({
                    children: [new Paragraph("3,4")],
                }),
                new TableCell({
                    children: [new Paragraph("3,5")],
                }),
            ],
        }),
        new TableRow({
            children: [
                new TableCell({
                    children: [new Paragraph("4,0")],
                }),
                
                new TableCell({
                    children: [new Paragraph("4,2")],
                }),
                new TableCell({
                    children: [new Paragraph("4,3")],
                }),
                new TableCell({
                    children: [new Paragraph("4,4")],
                }),
                new TableCell({
                    children: [new Paragraph("4,5")],
                }),
            ],
        }),
        new TableRow({
            children: [
                new TableCell({
                    children: [],
                }),
                new TableCell({
                    children: [],
                }),
                new TableCell({
                    children: [],
                }),
                new TableCell({
                    children: [],
                }),
                new TableCell({
                    children: [],
                }),
                new TableCell({
                    children: [],
                }),
            ],
        }),
    ],
});

doc.addSection({
    children: [table2],
});

Packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("My Document1.docx", buffer);
});
```

The result: 
![image](https://user-images.githubusercontent.com/4921608/66733271-90e36100-ee91-11e9-865a-5d82839ffce6.png)

v5.0.0-rc7

**Comment by dolanmiu** [comment] 2019-10-14 10:09
Noted, will take a look

**Comment by dolanmiu** [comment] 2020-02-20 22:54
Duplicate of https://github.com/dolanmiu/docx/issues/456

Closing this one

**Closed by dolanmiu** 2020-02-20 22:54 UTC
Labels: bug
