### ISSUE TITLE
Unable to run the code on IE 10

### ISSUE THREAD

**Issue by manpreetsinghbhatia** [dolanmiu/docx#271] opened 2019-02-22 18:48 UTC

**Comment by manpreetsinghbhatia** [comment] 2019-02-22 18:56
Unable to get property 'call' of undefined or null reference

**Comment by dolanmiu** [comment] 2019-02-22 20:58
duplicate of:

https://github.com/dolanmiu/docx/pull/241

**Closed by dolanmiu** 2019-02-22 20:58 UTC
