### ISSUE TITLE
Error in IE

### ISSUE THREAD

**Issue by laura301091** [dolanmiu/docx#318] opened 2019-04-30 10:39 UTC
Unable to run code on IE.  It loads a blank screen with an error of syntax error on vendor.js on class DocumentAttributes.

I've tried changing the tsconfig.json file to use es5 and 
 "lib": [
      "es2015",
      "dom"
    ]
but still doesn't work.

Is there a fix for this?

**Comment by dolanmiu** [comment] 2019-08-08 23:14
Duplicate of: https://github.com/dolanmiu/docx/issues/240

**Closed by dolanmiu** 2019-08-08 23:14 UTC
