### ISSUE TITLE
Hyperlink color and font style

### ISSUE THREAD

**Issue by omgovich** [dolanmiu/docx#617] opened 2020-08-13 20:32 UTC
Hi, according to the docs, developers were able to change a link's style and color:
```js
hyperlink.TextRun.bold();
hyperlink.TextRun.color('2266ff');
```

But looks like this code is no longer supported:
```
TypeError: hyperlink.textRun.bold is not a function
TypeError: hyperlink.textRun.color is not a function
```

Are there any ways to change these properties in the latest versions? Thanks!

**Comment by HTrayford** [comment] 2020-08-19 22:23
@omgovich you can set the text property to a TextRun and style it that way:

`{
  link: 'http://www.example.com',
  type: HyperlinkType.EXTERNAL,
  text: new TextRun({
    text: 'Go to example.com',
    bold: true,
    color: '22266ff',
    size: 32,
    font: { name: 'Calibri' }
}`

**Comment by BrentFarese** [comment] 2020-10-31 13:36
> @omgovich you can set the text property to a TextRun and style it that way:
> 
> `{
> 
> ```
> link: 'http://www.example.com',
> type: HyperlinkType.EXTERNAL,
> text: new TextRun({
>   text: 'Go to example.com',
>   bold: true,
>   color: '22266ff',
>   size: 32,
>   font: { name: 'Calibri' }
> ```
> 
> }`

It would be awesome if this was documented!  Perhaps I'll submit a PR.  Great library by the way.

**Comment by BrentFarese** [comment] 2020-10-31 15:11
@HTrayford what if your link contains text runs with different styles?  Is it possible to create hyperlinks in DOCX that have text with different styles inside the hyperlink?  It seems to me that hyperlink should be able to have `children` that is an array of `TextRun`.  Thanks!

**Comment by HTrayford** [comment] 2020-11-01 17:14
Children as text runs might be really handy.  I don't think multiple styles is supported, but haven't tried.  As a work around, you could create multiple hyperlinks that go to the same location each with their own styling.  A bit of a hack, but I think it would work if you needed it.

**Comment by BrentFarese** [comment] 2020-11-02 17:07
@HTrayford thanks for the suggestion.  It seems, however, your original suggestion I don't think is supported.  The `text` key only appears to take a `string` and not a `TextRun`.  See [here](https://github.com/dolanmiu/docx/blob/37e610d2b3beacef8d6f64f0890f74a4d387a4b9/src/file/core-properties/properties.ts#L33).  So, I am unsure how to style text content within links at all.  @dolanmiu is it possible to style text inside links declaratively?  Glad to submit a PR to update documentation or to perhaps try a PR to support text styling in links if it's not implemented.  Thanks!

**Comment by HTrayford** [comment] 2020-11-02 20:32
I am using this technique to format nearly 100 hyperlinks in various documents, so it definitely works.  I am not using Type Script though, so perhaps the type checking is what is causing your troubles.  Based on that, a PR that updates the type definitions to accept either a string or a TextRun, might be enough to get things working with Type Script, though allowing the hyperlink to accept a children array of TextRun would be much more flexible.

**Comment by BrentFarese** [comment] 2020-11-02 21:47
Thank you @HTrayford.  I can confirm that it does indeed work, but that the TS types may be wrong.  We are predominantly a TS project but I tried your approach and then just added a type assertion to appease the TypeScript compiler and it does style the link correctly.

I **_think_** it works because [options.hyperlinks](https://github.com/dolanmiu/docx/blob/37e610d2b3beacef8d6f64f0890f74a4d387a4b9/src/file/file.ts#L153) calls [this.createHyperlink](https://github.com/dolanmiu/docx/blob/37e610d2b3beacef8d6f64f0890f74a4d387a4b9/src/file/file.ts#L216) passing in the `TextRun` as the `text` parameter (typed as `string`) to [new Hyperlink](https://github.com/dolanmiu/docx/blob/37e610d2b3beacef8d6f64f0890f74a4d387a4b9/src/file/file.ts#L217).  Then, `Hyperlink` [creates a TextRun](https://github.com/dolanmiu/docx/blob/37e610d2b3beacef8d6f64f0890f74a4d387a4b9/src/file/paragraph/links/hyperlink.ts#L32) passing down the `TextRun` on the `text` param, which calls [super(options)](https://github.com/dolanmiu/docx/blob/37e610d2b3beacef8d6f64f0890f74a4d387a4b9/src/file/paragraph/run/text-run.ts#L12).  After that point, I get a bit lost in the inheritance stack of all the Classes.

It either works by happenstance or the types are simply incorrect.  Maybe @dolanmiu can shed some light?

**Comment by dolanmiu** [comment] 2020-11-04 18:23
> @dolanmiu is it possible to style text inside links declaratively? Glad to submit a PR to update documentation or to perhaps try a PR to support text styling in links if it's not implemented. Thanks!

Yes, if you can do this, that would be great

**Comment by dolanmiu** [comment] 2021-02-27 19:26
Now hyperlinks are entirely fully customizable, you can change it to whatever style you want.

Hyperlinks now take a `child` component, which means hyperlinks can even be images etc!

Will be fixed by:

https://github.com/dolanmiu/docx/pull/784

**Closed** 2021-02-28 15:53 UTC
