### ISSUE TITLE
Error with docx and browserify

### ISSUE THREAD

**Issue by quentin2k29** [dolanmiu/docx#35] opened 2017-05-31 12:37 UTC
Hi, 
I'm working on a project and I use Angularjs with Cordova. So I tried to put docx in a bundle with browserify but I got an error when I execute the code.

Everything is fine when browserify create the bundle but I get an error when the app use the bundle :

`TypeError: fs$ReadStream is undefined line 14056`

I checked the code and the variable legstream is undefined so I think the error comes from the legacy(fs) but I don't know why.

 ```
 if (process.version.substr(0, 4) === 'v0.8') {
    var legStreams = legacy(fs)
    ReadStream = legStreams.ReadStream
    WriteStream = legStreams.WriteStream
  }

 var fs$ReadStream = fs.ReadStream
 console.log(legStreams);
 ReadStream.prototype = Object.create(fs$ReadStream.prototype)
 ReadStream.prototype.open = ReadStream$open

```
If someone already had this problem or used this module with browserify and can help me, thanks :)

**Comment by dolanmiu** [comment] 2017-05-31 12:58
Unfortunately, this library does not work with browser based environment. Aka no Angular, no react etc. This is because it internally uses `archiver` which uses `fs`.

`fs` only exists in node.js, hence why you are getting this error!

**Comment by quentin2k29** [comment] 2017-05-31 13:37
Thanks for you quick answer ! Do you know an other solution for creating and saving a .docx file using Angular and Cordova ?

**Comment by dolanmiu** [comment] 2017-05-31 14:16
Not that I know of, the problem is, a .docx file is actually a .zip file, try it! Rename a .docx to .zip, right click > extract all 😂😂

The problem is... all zipping functionality is not supported by browsers for JavaScript. Probably for security reasons

If you find a way, let me know; and I'll add it!

**Comment by dolanmiu** [comment] 2018-01-25 17:44
Closing as `docx` does not support browser environment due to it accessing file system:

https://github.com/archiverjs/node-archiver/issues/224

**Closed by dolanmiu** 2018-01-25 17:44 UTC

**Comment by kharmonycentral** [comment] 2018-09-17 23:11
Was just reading through some issues and found this discussion. Since the latest release, I see now in the documentation that it mentions running docx in the browser environment (for example in the Packer text: "It works in both a node and browser environment (Angular etc)").

Can you (@dolanmiu) provide a little more info or include something in the docs for how to get it running in the browser environments (such as AngularJS)? I tried including the docx files in my scripts and then referencing it in my controllers, but I couldn't get it to work. Thank you again for your time!

**Comment by dolanmiu** [comment] 2018-09-18 01:10
Yup! As of `4.0.0` `docx` works on the browser 😄 

https://codepen.io/anon/pen/dqoVgQ
https://jsfiddle.net/3xhezb5w/2

**Comment by Philipotieno** [comment] 2020-06-12 18:47
@dolanmiu how can I use it with react

**Comment by dolanmiu** [comment] 2020-06-13 19:36
Seems like it does not work with React at the moment due to ES5 issues
