### ISSUE TITLE
Render formula

### ISSUE THREAD

**Issue by ferlolo** [dolanmiu/docx#344] opened 2019-06-26 11:59 UTC
Hi, is there any way to render some formula and that the office interpret it?

Regards!

**Comment by dolanmiu** [comment] 2019-06-26 16:27
Duplicate of:

https://github.com/dolanmiu/docx/issues/290

**Comment by dolanmiu** [comment] 2019-07-10 05:50
Closing because of duplicate

**Closed by dolanmiu** 2019-07-10 05:50 UTC
